replicaCount: 2

image:
  repository: m8122000/go_app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 9090

persistence:
  enabled: true
  existingClaim: "mysql-data-pvc"

ingress:
  enabled: false

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

mysql:
  host: db
  user: root
  password: secret
  port: 3306

resources: {}
